name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: dtolnay/rust-toolchain@master
      with:
        toolchain: 1.70.0
        components: clippy, rustfmt
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-build-1.70.0-${{ hashFiles('**/Cargo.toml') }}
    - name: Install alsa and udev
      run: sudo apt-get update; sudo apt-get install --no-install-recommends libasound2-dev libudev-dev libwayland-dev libxkbcommon-dev
      if: runner.os == 'linux'
    - name: Build
      run: cargo build --verbose --workspace --features "bevy/x11"
#     - name: Run tests
#       run: cargo test --verbose --workspace
    - name: Run fmt check
      run: cargo fmt --all -- --check
    - name: Run clippy
      run: cargo clippy --workspace --all-targets --all-features --features "bevy/x11" -- --deny warnings
